export const LOGOS_BASE_URL = 'assets/partner-logo/'
export const INITIATIVE_CLINICS_LOGOS = ['logo-medizin.svg', 'logo-bmbf.svg']
export const PARTICIPANT_CLINICS_LOGOS = [
  'logo-aachen.jpg',
  'logo-augsburg.jpg',
  'logo-berlin.jpg',
  'logo-bonn.jpg',
  'logo-dresden.jpg',
  'logo-duesseldorf.jpg',
  'logo-erlangen.jpg',
  'logo-essen.jpg',
  'logo-frankfurt.jpg',
  'logo-freiburg.jpg',
  'logo-giessen-marburg.jpg',
  'logo-goettingen.jpg',
  'logo-halle_saale.jpg',
  'logo-greifswald.jpg',
  'logo-hamburg.jpg',
  'logo-hannover.jpg',
  'logo-heidelberg.jpg',
  'logo-jena.jpg',
  'logo-koeln.jpg',
  'logo-leipzig.jpg',
  'logo-magdeburg.jpg',
  'logo-mainz.jpg',
  'logo-mannheim.jpg',
  'logo-muenchen-lmu.jpg',
  'logo-muenchen-tum_mri.jpg',
  'logo-muenster.jpg',
  'logo-regensburg.jpg',
  'logo-rostock.jpg',
  'logo-saarland.jpg',
  'logo-schleswig-holstein.jpg',
  'logo-tuebingen.jpg',
  'logo-ulm.jpg',
  'logo-wuerzburg.jpg',
]
