name: 'Documentation feedback / bug'
description: 'You found an error in ou documentation or want to give feedback about its content.'
title: '[Docs]: '
labels: ['docs']
body:
  - type: markdown
    attributes:
      value: 'Thanks for your contribution and help making our docs better'
  - type: input
    id: contact
    attributes:
      label: 'Contact details'
      description: 'Please tell us how we can contact you if we have further questions.'
      placeholder: 'Example: jon.doe@example.com'
  - type: dropdown
    id: 'section'
    attributes:
      label: 'Docs section'
      description: 'On which section of the docs you want to give feedback or contains an error?'
      options:
        - 'General'
        - '01 - Create user'
        - '02 - Welcome'
        - '03 - Search'
        - '04 - Projects'
        - '05 - Data explorer'
        - '06 - Criteria'
        - '07 - User management'
        - '08 - Organizations'
        - '09 - Content editor'
        - '10 - Manager Tools'
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: 'Description'
      description: 'Describe your feedback or the error.'
