import {
  faMicroscope,
  faBars,
  faGlobeEurope,
  faCog,
  faSignOutAlt,
  faSignInAlt,
  faDna,
  faPlus,
  faSearch,
  faTimesCircle,
  faTimes,
  faCheck,
  faTrash,
  faAngleRight,
  faEllipsisV,
  faClock,
  faUser,
  faTable,
  faExternalLinkAlt,
  faUserLock,
  faAlignLeft,
  faPlay,
  faPen,
  faExclamationCircle,
  faBuilding,
  faUserEdit,
  faFileDownload,
  faCaretSquareUp,
  faArrowsAlt,
  faExclamationTriangle,
  faArrowDown,
  faExternalLinkSquareAlt,
  faChartPie,
  faUndo,
  faInfoCircle,
  faClipboard,
  faQuestionCircle,
  faUserCircle,
  faBookOpen,
  faPaperclip,
} from '@fortawesome/free-solid-svg-icons'

import { faNewspaper, faCheckCircle, faEye, faHospital } from '@fortawesome/free-regular-svg-icons'

export const FONT_AWESOME_SOLID_ICONS = [
  faMicroscope,
  faBars,
  faGlobeEurope,
  faCog,
  faSignOutAlt,
  faSignInAlt,
  faDna,
  faPlus,
  faSearch,
  faTimesCircle,
  faTimes,
  faCheck,
  faTrash,
  faAngleRight,
  faEllipsisV,
  faClock,
  faUser,
  faUserCircle,
  faTable,
  faExternalLinkAlt,
  faUserLock,
  faAlignLeft,
  faPlay,
  faPen,
  faExclamationCircle,
  faBuilding,
  faUserEdit,
  faFileDownload,
  faCaretSquareUp,
  faArrowsAlt,
  faExclamationTriangle,
  faArrowDown,
  faExternalLinkSquareAlt,
  faChartPie,
  faUndo,
  faInfoCircle,
  faClipboard,
  faQuestionCircle,
  faBookOpen,
  faPaperclip,
]

export const FONT_AWESOME_REGULAR_ICONS = [faNewspaper, faCheckCircle, faEye, faHospital]

export const FONT_AWESOME_ICONS = [...FONT_AWESOME_SOLID_ICONS, ...FONT_AWESOME_REGULAR_ICONS]
