export enum ProjectCategory {
  Pediatrics = 'PEDIATRICS',
  Symptomatology = 'SYMPTOMATOLOGY',
  ClassificationOfDiseaseProgression = 'CLASSIFICATION_OF_DISEASE_PROGRESSION',
  DrugTherapies = 'DRUG_THERAPIES',
  SurgicalTherapies = 'SURGICAL_THERAPIES',
  TreatmentPlan = 'TREATMENT_PLAN',
  AlternativeTherapies = 'ALTERNATIVE_THERAPIES',
  Prevention = 'PREVENTION',
  DiagnosticMethodology = 'DIAGNOSTIC_METHODOLOGY',
  DrugSideEffects = 'DRUG_SIDE_EFFECTS',
  Microbiology = 'MICROBIOLOGY',
  Pathology = 'PATHOLOGY',
  Oncology = 'ONCOLOGY',
  RareDiseases = 'RARE_DISEASES',
  DecisionSupport = 'DECISION_SUPPORT',
  Covid19 = 'COVID19',
  CriticalCareMedicine = 'CRITICAL_CARE_MEDICINE',
  QualityManagementMii = 'QUALITY_MANAGEMENT_MII',
  QualityManagementRoutineCare = 'QUALITY_MANAGEMENT_ROUTINE_CARE',
  LongitudinalProject = 'LONGITUDINAL_PROJECT',
  ProspectiveProject = 'PROSPECTIVE_PROJECT',
  RetrospectiveProject = 'RETROSPECTIVE_PROJECT',
  Registry = 'REGISTRY',
}
