name: Release new tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        run: |
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/num-portal-webapp:${{ github.ref_name }} -DskipTests
          docker tag ${{ secrets.DOCKER_USERNAME }}/num-portal-webapp ${{ secrets.DOCKER_USERNAME }}/num-portal-webapp:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/num-portal-webapp:${{ github.ref_name }}

          echo "### :rocket: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
